### ISSUE TITLE
Moving as you have a spell on top of you crashes game

### ISSUE THREAD

**Issue by Pheelbert** [Pheelbert/battlenetwork#10]
![asssert](https://user-images.githubusercontent.com/5648665/39261936-fd8b22aa-488b-11e8-95c9-5a0f1c1ddc7f.PNG)

**Comment by TheMaverickProgrammer** [comment]
This has not happened for my code and I've tried. Maybe your new changes have this. Will pull and test your code later this weekend to confirm.

**Comment by Pheelbert** [comment]
You're right although the behavior isn't the wanted one either. The wave should do damage as soon as it comes into contact with the player, previously it would allow the player to move outside the tile without being hit. So, not sure if the fix is easier or harder before my change.

**Comment by TheMaverickProgrammer** [comment]
I just merged with your master branch and am not experiencing this issue. I have moved in and out of waves like usual even when they're right on top. IIRC waves only did damage at the last frame. No runtime error yet.

**Comment by TheMaverickProgrammer** [comment]
I found something in my playthrough. Moving off a cracked panel in the front row got "hit" by a wave even though I was no longer on that panel. I think in the movement code I may have added another pointer to a tile for Mega and that might be the issue of the crash.

**Comment by TheMaverickProgrammer** [comment]
Had this happen today. Got an error about std::vector index out of range or the like. Which is strange because the vector is not modified during the AffectEntities() loop so the iterator shouldn't fail like it does.

**Comment by TheMaverickProgrammer** [comment]
Just noticed something. I dunno if vector has an operator for `iter < list.end()`. The signature is usually `iter != list.end()`. There's also the chance the entity vector is modified during `caller->Attack()` which would cause problems.
