### ISSUE TITLE
Accurate chip screen impossible to do with current engine design

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [Pheelbert/battlenetwork#13]
See #5 on my [improvements task wiki](https://github.com/TheMaverickProgrammer/battlenetwork/wiki/Improvement-Tasks).

This is a request for an enhancement. We should have Scene (really just a scene node itself) that renders scene nodes (previously called drawables). We should allow the engine to support multiple scenes so we can pull off moving UI layers.

I propose the following roadmap for this change:

* Engine has list of Scenes
* Scene is a SceneNode with list of SceneLayers (implies Scenes can be moved around)
* Scene Layer is a draw-ordered list of SceneNodes
* SceneNodes are Drawables by a different name
* Entity signature should be redesigned to reflect "Entity : public SceneNode"

We'll need an intuitive API to add scenes into the engine, pop scenes, add layers to scenes, reorder layers, select layers, and apply shaders to each individual (Therefore SceneNode has a pointer to a shader just as Layered Drawable currently does). This will also affect the Engine Draw pipeline.

This will allow us to have true mmbn effects when in chip cust and in a pause menu.

If you can work on this, I'll write a shader resource manager. And if you have time for some fun, [checkout my loading screen solution](https://github.com/TheMaverickProgrammer/battlenetwork/tree/loading-screen). I think you'll enjoy it.

**Comment by Pheelbert** [comment]
I like the idea of the loading screen! Can't wait to see how it'll look like in the near future :). I'll definitively look into this, but I'll be out for the weekend. Good luck on everything 🥇

**Comment by TheMaverickProgrammer** [comment]
You can pull and run it. It works already.

**Comment by Pheelbert** [comment]
Oh well I was having an issue I believe, but I did see something. I'll give details on that and investigate more later!
