### ISSUE TITLE
Use spaces instead of tabs and indent correctly everywhere

### ISSUE THREAD

**Issue by Pheelbert** [Pheelbert/battlenetwork#5]

**Comment by Pheelbert** [comment]
@TheMaverickProgrammer I'll reformat everything using visual studio formatting shortcut. I code using this format for a while which is very similar to Google' style guide

**Comment by TheMaverickProgrammer** [comment]
I'm not familiar with VC. I usually use free code editors and spaces so I'm surprised there are tabs. How do I replace tabs for spaces?

**Comment by Pheelbert** [comment]
Normally you can find it in the options for text editor

![image](https://user-images.githubusercontent.com/5648665/38829927-a840979e-4188-11e8-9076-cc54fc62ccec.png)

I have trouble working on things that aren't formatted the same everywhere, and since then I've adopted a different style that I find much easier to read (https://google.github.io/styleguide/cppguide.html). I hope you won't have issues with the change.. I wouldn't want to push you away from working on this just for "my" formatting standards.

**Comment by TheMaverickProgrammer** [comment]
That's fine
