### ISSUE TITLE
OpenAL issue sometimes when running

### ISSUE THREAD

**Issue by Pheelbert** [Pheelbert/battlenetwork#7]
![image](https://user-images.githubusercontent.com/5648665/39016326-17945fc4-43ee-11e8-9027-4c15078faeed.png)

**Comment by TheMaverickProgrammer** [comment]
I've seen the same problem too. This seems to be an SFML problem.

**Comment by Pheelbert** [comment]
I turned off my antivirus and I don't get these weird errors happening anymore. It seems like it was trying to sandbox the game once in a while so this would happen.
